spring:

# ==== DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    show_sql: true

  jackson:
    time-zone: Asia/Seoul

  # ==== Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000 #1시간
  refresh-token-expiration: 1296000000 #15일