spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000 #1시간
  refresh-token-expiration: 1296000000 #15일